connections {
    ipv6-ike {
        version = 2
        local_addrs  = fd77:77:0::20
        remote_addrs = fd77:77:0::10
        proposals = aes256-sha384-modp2048
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            ipv6-child {
                local_ts = 10.77.2.0/24,fd77:77:2::/64
                remote_ts = 10.77.1.0/24,fd77:77:1::/64
                esp_proposals = aes256-sha384-modp2048
                mode = tunnel
                start_action = none
            }
        }
    }
}
