connections {
    T07 {
        version = 2
        local_addrs  = 10.77.0.20
        remote_addrs = 10.77.0.10
        proposals = aes128gcm16-prfsha256-ecp256
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            t07-child {
                local_ts = 10.77.0.20/32
                remote_ts = 10.77.0.10/32
                esp_proposals = aes128gcm16-modp2048
                mode = transport
                start_action = none
            }
        }
    }
}

