connections {
    T11 {
        version = 2
        local_addrs  = fd77:77:0::20
        remote_addrs = fd77:77:0::10
        proposals = aes128gcm16-prfsha256-modp3072
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            t11-child {
                local_ts = 10.77.16.0/24
                remote_ts = 10.77.15.0/24
                esp_proposals = aes128gcm16-modp2048
                mode = tunnel
                start_action = none
            }
        }
    }
}

