connections {
    T12 {
        version = 2
        local_addrs  = 10.77.0.20
        remote_addrs = 10.77.0.10
        proposals = aes128-sha256-ecp256
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            t12-child {
                local_ts = 10.77.18.0/24
                remote_ts = 10.77.17.0/24
                esp_proposals = aes128-sha256-ecp256
                mode = tunnel
                start_action = none
            }
        }
    }
}

