connections {
    T14 {
        version = 2
        local_addrs  = 10.77.0.20
        remote_addrs = 10.77.0.10
        proposals = aes256-sha512-modp3072
        rekey_time = 60s
        reauth_time = 0
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            t14-child {
                local_ts = 10.77.26.0/24
                remote_ts = 10.77.25.0/24
                esp_proposals = aes256-sha256-modp3072
                mode = tunnel
                rekey_time = 60s
                life_time = 70s
                start_action = none
            }
        }
    }
}
