connections {
    T02 {
        version = 2
        local_addrs  = 10.77.0.10
        remote_addrs = 10.77.0.20
        proposals = aes128-sha256-modp2048
        local {
            auth = psk
            id = gateway-a
        }
        remote {
            auth = psk
            id = gateway-b
        }
        children {
            t02-child {
                local_ts = 10.77.21.0/24
                remote_ts = 10.77.22.0/24
                esp_proposals = aes128-sha256-modp2048
                mode = tunnel
                start_action = none
            }
        }
    }
}

