connections {
    T05 {
        version = 2
        local_addrs  = 10.77.0.10
        remote_addrs = 10.77.0.20
        proposals = aes256gcm16-prfsha256-modp3072
        local {
            auth = psk
            id = gateway-a
        }
        remote {
            auth = psk
            id = gateway-b
        }
        children {
            t05-child {
                local_ts = 10.77.13.0/24
                remote_ts = 10.77.14.0/24
                esp_proposals = aes256gcm16-modp2048
                mode = tunnel
                start_action = none
            }
        }
    }
}

