connections {
    T09 {
        version = 2
        local_addrs  = 10.77.0.10
        remote_addrs = 10.77.0.20
        proposals = aes256-sha384-modp2048
        local {
            auth = psk
            id = gateway-a
        }
        remote {
            auth = psk
            id = gateway-b
        }
        children {
            t09-child {
                local_ts = 10.77.0.10/32
                remote_ts = 10.77.0.20/32
                ah_proposals = sha256
                mode = transport
                start_action = none
            }
        }
    }
}

