connections {
    T13 {
        version = 2
        local_addrs  = 10.77.0.10
        remote_addrs = 10.77.0.20
        proposals = aes128-sha384-modp3072
        local {
            auth = psk
            id = gateway-a
        }
        remote {
            auth = psk
            id = gateway-b
        }
        children {
            t13-child {
                local_ts = 10.77.19.0/24
                remote_ts = 10.77.20.0/24
                esp_proposals = aes128-sha384-modp2048
                mode = tunnel
                start_action = none
            }
        }
    }
}

