connections {
    T15 {
        version = 2
        local_addrs = 10.77.0.20
        remote_addrs = 10.77.0.10
        proposals = aes192-sha256-modp3072
        local {
            auth = psk
            id = gateway-b
        }
        remote {
            auth = psk
            id = gateway-a
        }
        children {
            t15-child {
                local_ts = fd77:77:24::/64
                remote_ts = fd77:77:23::/64
                esp_proposals = aes192-sha256
                mode = tunnel
                start_action = none
                close_action = none
            }
        }
    }
}

secrets {
    ike-psk {
        id-a = gateway-a
        id-b = gateway-b
        secret = "SihIpsecPsk2026-Phase1-Baseline!"
    }
}
